/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author Ernesto
 */
public class VentanaAgregarProducto extends javax.swing.JFrame {
    
    String nombre; 
    String descripcion;
    double costoCompra;
    double porcentajeGanancia; 
    double impuesto;
    int cantidad;
    /**
     * Creates new form VentanaAgregarProducto
     */
    public VentanaAgregarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    */
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        InsertButton = new javax.swing.JButton("Insertar");
        nombreProducto = new javax.swing.JTextField();
        descripcionProducto = new javax.swing.JTextField();
        costoCompraProducto = new javax.swing.JTextField();
        porcentajeGananciaProducto = new javax.swing.JTextField();
        impuestoProducto = new javax.swing.JTextField();
        cantidadProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel("Nombre:");
        jLabel2 = new javax.swing.JLabel("Descripción:");
        jLabel3 = new javax.swing.JLabel("Costo Compra:");
        jLabel4 = new javax.swing.JLabel("Porcentaje Ganancia:");
        jLabel5 = new javax.swing.JLabel("Impuesto:");
        jLabel6 = new javax.swing.JLabel("Cantidad:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Producto");

        // Estilo del Panel
        jPanel1.setBackground(new Color(240, 248, 255));  // Azul muy claro
        jPanel1.setBorder(new LineBorder(new Color(100, 149, 237), 2, true));

        // Configuración de los JTextField
        configurarCampoTexto(nombreProducto, "Ingrese nombre");
        configurarCampoTexto(descripcionProducto, "Ingrese descripción");
        configurarCampoTexto(costoCompraProducto, "Ingrese costo de compra");
        configurarCampoTexto(porcentajeGananciaProducto, "Ingrese porcentaje de ganancia");
        configurarCampoTexto(impuestoProducto, "Ingrese impuesto");
        configurarCampoTexto(cantidadProducto, "Ingrese cantidad");

        // Agregar el evento de focus a los JTextField
        agregarEventoFocus(nombreProducto, "Ingrese nombre");
        agregarEventoFocus(descripcionProducto, "Ingrese descripción");
        agregarEventoFocus(costoCompraProducto, "Ingrese costo de compra");
        agregarEventoFocus(porcentajeGananciaProducto, "Ingrese porcentaje de ganancia");
        agregarEventoFocus(impuestoProducto, "Ingrese impuesto");
        agregarEventoFocus(cantidadProducto, "Ingrese cantidad");

        // Configuración de los JLabel
        configurarEtiqueta(jLabel1);
        configurarEtiqueta(jLabel2);
        configurarEtiqueta(jLabel3);
        configurarEtiqueta(jLabel4);
        configurarEtiqueta(jLabel5);
        configurarEtiqueta(jLabel6);

        // Botón Insertar Estilizado
        InsertButton.setFont(new Font("Arial", Font.BOLD, 14));
        InsertButton.setBackground(new Color(70, 130, 180));  // Azul oscuro
        InsertButton.setForeground(Color.WHITE);
        InsertButton.setBorder(new LineBorder(new Color(25, 25, 112), 2, true));

        // Evento para capturar los datos al presionar el botón
        InsertButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Captura los datos de los campos de texto
                guardarDatos();
                // Inserta el producto en la base de datos
                prueba.insertProducto(nombre, descripcion, costoCompra, porcentajeGanancia, impuesto, cantidad);

                // Muestra un mensaje de confirmación
                JOptionPane.showMessageDialog(null, "Producto guardado correctamente.");

                // Resetea los campos de texto
                resetearCampos();

                // Opcional: Obtener y mostrar el último producto insertado
                prueba.getLastProducto();
            }
        });

        // Diseño del Panel
        GroupLayout layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);

        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(nombreProducto, 150, 150, 150))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(descripcionProducto, 150, 150, 150))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(costoCompraProducto, 150, 150, 150))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(porcentajeGananciaProducto, 150, 150, 150))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(impuestoProducto, 150, 150, 150))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(cantidadProducto, 150, 150, 150)))
                .addComponent(InsertButton, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        );

        layout.setVerticalGroup(
            layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProducto, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionProducto, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addComponent(costoCompraProducto, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentajeGananciaProducto, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addComponent(impuestoProducto, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadProducto, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                .addGap(20)
                .addComponent(InsertButton, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1);
        pack();
        setLocationRelativeTo(null);  // Centrar la ventana
    }

// Método para capturar los datos cuando se presiona "Insertar"
    private void guardarDatos() {
        nombre = nombreProducto.getText();
        descripcion = descripcionProducto.getText();
        costoCompra = Double.parseDouble(costoCompraProducto.getText());
        cantidad = Integer.parseInt(cantidadProducto.getText());
        porcentajeGanancia=Double.parseDouble(porcentajeGananciaProducto.getText());
        impuesto=Double.parseDouble(impuestoProducto.getText());
        JOptionPane.showMessageDialog(this, 
        "Datos Guardados:\nNombre: " + nombre + "\nDescripción: " + descripcion +
        "\nPrecio: " + costoCompra + "\nStock: " + cantidad,
        "Información", JOptionPane.INFORMATION_MESSAGE);
    }

// Método para restablecer los campos de texto a sus valores iniciales
    private void resetearCampos() {
    // Restablecer el campo de nombre
    nombreProducto.setText("Ingrese nombre");
    nombreProducto.setForeground(Color.GRAY);

    // Restablecer el campo de descripción
    descripcionProducto.setText("Ingrese descripción");
    descripcionProducto.setForeground(Color.GRAY);

    // Restablecer el campo de costo de compra
    costoCompraProducto.setText("Ingrese costo de compra");
    costoCompraProducto.setForeground(Color.GRAY);

    // Restablecer el campo de porcentaje de ganancia
    porcentajeGananciaProducto.setText("Ingrese porcentaje de ganancia");
    porcentajeGananciaProducto.setForeground(Color.GRAY);

    // Restablecer el campo de impuesto
    impuestoProducto.setText("Ingrese impuesto");
    impuestoProducto.setForeground(Color.GRAY);

    // Restablecer el campo de cantidad
    cantidadProducto.setText("Ingrese cantidad");
    cantidadProducto.setForeground(Color.GRAY);
    }

// Métodos para configurar los JTextField y JLabel
    private void configurarCampoTexto(JTextField campo, String placeholder) {
    campo.setText(placeholder);
    campo.setFont(new Font("Arial", Font.PLAIN, 14));
    campo.setForeground(Color.GRAY);
    campo.setBorder(new LineBorder(new Color(100, 149, 237), 2, true));
    }

    private void configurarEtiqueta(JLabel etiqueta) {
    etiqueta.setFont(new Font("Arial", Font.BOLD, 14));
    etiqueta.setForeground(new Color(25, 25, 112));
    }
    private void agregarEventoFocus(JTextField campo, String placeholder) {
        campo.addFocusListener(new java.awt.event.FocusListener() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (campo.getText().equals(placeholder)) {
                    campo.setText(""); // Borra el texto cuando hace clic
                    campo.setForeground(Color.BLACK); // Cambia el color del texto a negro
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (campo.getText().trim().isEmpty()) {
                    campo.setText(placeholder); // Restaura el texto si está vacío
                    campo.setForeground(Color.GRAY); // Mantiene el color gris
                }
            }
        });
    }

// Variables declaration - do not modify                     
private javax.swing.JButton InsertButton;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JTextField descripcionProducto;
    private javax.swing.JTextField costoCompraProducto;
    private javax.swing.JTextField porcentajeGananciaProducto;
    private javax.swing.JTextField impuestoProducto;
    private javax.swing.JTextField cantidadProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private pruebaSQL prueba;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
